
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Label in_lab;

	private global::Gtk.HBox hbox2;

	private global::Gtk.SpinButton min;

	private global::Gtk.HBox hbox3;

	private global::Gtk.Label min_lab;

	private global::Gtk.Button ok_btn;

	private global::Gtk.HBox hbox4;

	private global::Gtk.ProgressBar progress;

	private global::Gtk.Button stop_btn;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Спати");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Resizable = false;
		this.AllowGrow = false;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		this.vbox1.BorderWidth = ((uint)(4));
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.in_lab = new global::Gtk.Label();
		this.in_lab.Name = "in_lab";
		this.in_lab.Xpad = 3;
		this.in_lab.Ypad = 3;
		this.in_lab.LabelProp = global::Mono.Unix.Catalog.GetString("Через");
		this.hbox1.Add(this.in_lab);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.in_lab]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.min = new global::Gtk.SpinButton(0D, 1440D, 1D);
		this.min.CanFocus = true;
		this.min.Name = "min";
		this.min.Adjustment.PageIncrement = 10D;
		this.min.ClimbRate = 5D;
		this.min.Numeric = true;
		this.min.Value = 70D;
		this.hbox2.Add(this.min);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.min]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.min_lab = new global::Gtk.Label();
		this.min_lab.Name = "min_lab";
		this.min_lab.LabelProp = global::Mono.Unix.Catalog.GetString("хв.");
		this.hbox3.Add(this.min_lab);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.min_lab]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		this.hbox2.Add(this.hbox3);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.hbox3]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.ok_btn = new global::Gtk.Button();
		this.ok_btn.WidthRequest = 95;
		this.ok_btn.CanFocus = true;
		this.ok_btn.Name = "ok_btn";
		this.ok_btn.UseUnderline = true;
		this.ok_btn.Label = global::Mono.Unix.Catalog.GetString("Вимкнути");
		this.hbox2.Add(this.ok_btn);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.ok_btn]));
		w5.Position = 2;
		w5.Expand = false;
		w5.Fill = false;
		w5.Padding = ((uint)(6));
		this.hbox1.Add(this.hbox2);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.hbox2]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		this.vbox1.Add(this.hbox1);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 9;
		// Container child hbox4.Gtk.Box+BoxChild
		this.progress = new global::Gtk.ProgressBar();
		this.progress.WidthRequest = 153;
		this.progress.Name = "progress";
		this.progress.PulseStep = 0.0999999999999992D;
		this.hbox4.Add(this.progress);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.progress]));
		w8.Position = 0;
		w8.Expand = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.stop_btn = new global::Gtk.Button();
		this.stop_btn.WidthRequest = 95;
		this.stop_btn.CanFocus = true;
		this.stop_btn.Name = "stop_btn";
		this.stop_btn.UseUnderline = true;
		this.stop_btn.Label = global::Mono.Unix.Catalog.GetString("Скасувати");
		this.hbox4.Add(this.stop_btn);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.stop_btn]));
		w9.Position = 1;
		w9.Expand = false;
		w9.Fill = false;
		this.vbox1.Add(this.hbox4);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox4]));
		w10.PackType = ((global::Gtk.PackType)(1));
		w10.Position = 1;
		w10.Expand = false;
		w10.Fill = false;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 270;
		this.DefaultHeight = 76;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.ok_btn.Clicked += new global::System.EventHandler(this.Gotosleep);
		this.stop_btn.Clicked += new global::System.EventHandler(this.Stop);
	}
}
